### ISSUE TITLE
filemanager [maybe]: mc

### ISSUE THREAD

**Issue by m4u9** [ProjectGreybeard/bugs#14]
Leaning to not have file manager at all however I suggest midnight commander aka "mc". It's really small and has a nice enough TUI and kinda fits into the greybeards mindest :P

**Comment by sfalken** [comment]
I mean, I have no objection to mc or some sort of file manager.   I won't use it, but I have no objection to it being there.

**Comment by m4u9** [comment]
honestly I only brought it up for the lols. I don't actually use it and i am perfectly happy with just having bash =]

**Comment by mcepl** [comment]
Actually, I use it quite seriously ... I have still never found anything more convenient for browsing through RPM files and for browsing on remote SSH/Samba/etc shares.

**Comment by m4u9** [comment]
> Actually, I use it quite seriously ... I have still never found anything more convenient for browsing through RPM files and for browsing on remote SSH/Samba/etc shares.

I did not know it could browse SSH remotes. This is really useful! I should give it some serious try.
That said I have really nothing against adding it to the patterns. If none else creates the SR I will do so later.

**Comment by m4u9** [comment]
@mcepl forgot to ask, is there a way to make it handle automounting usb drives etc? Or is this more a gvfs thing?

**Comment by mcepl** [comment]
> @mcepl forgot to ask, is there a way to make it handle automounting usb drives etc? Or is this more a gvfs thing?

No, it is more automount/gvfs thing (the latter is a bit hard to set up without Gnome running, or could it be done?). I had this horrible ad hoc script:

```sh
#!/bin/sh
set -eu

[ -d /run/user/1000/gvfs/mtp:\/\/HMD_Global_Nokia_G10_PT99652AA11A1902644/ ] && exit 0

gio mount -li | grep mtp | awk -F= '{print $2}' | tr -s '\n' | sort -u \
    | xargs -I {} gio mount {}

# Apparently something needs to get settled down
sleep 5
```

But it never worked very reliably (see that `sleep 5` … that’s just me waving my hands in despair), and it doesn’t work now at all (I have probably some packages missing). `automount` is probably The Way™.

Besides, I am old enough to remember 1990s where here in the Central/Eastern Europe absolutely everybody had some clone of Norton Commander as their main file manager (who knows what happened to Vsevolod V. Volkov? Or who remembers [M602](https://www.cistepc.cz/m602-cesky-souborovy-manazer/)), so I don’t feel that much the need for “just plain command line” as many other Linux hackers have.

**Comment by sfalken** [comment]
At the moment, mc doesn't really "work" as a desktop application, as there is no "default terminal" set for xdg.    We get an mc.desktop file, which plays nice with the desktop launcher, but because `Terminal=True` doesn't do anything, you get a failure to launch.

See https://unix.stackexchange.com/a/590093 for an example of the issue

**Comment by mcepl** [comment]
Well, I see that @sysrich packaged [xdg-terminal-exec](https://build.opensuse.org/package/show/devel:microos/xdg-terminal-exec), which [seems to be finally supported by gio](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2839) (and closing [the legendary bug](https://gitlab.gnome.org/GNOME/glib/-/issues/338)).

So, could we get that package added to the Greybeard image with [configuration](https://github.com/Vladimir-csp/xdg-terminal-exec/) pointing to `foot`, please?

(I am not sure why the package is just in `devel:microos` and not in Factory, because it is certainly SUSE-wide problem).

**Comment by mcepl** [comment]
Actually, let me add -1 to this ticket: not to `xdg-terminal-exec` that is IMHO necessary, but to `mc`. We really should not encourage people to actually use the host system for anything. Command line is good enough for the system administration they should do.

**Comment by m4u9** [comment]
This was one of the reasons I was hesitant from the start. Your comment sort of reinforces my initial thoughts so let's close this
